# Generated by Django 5.1.2 on 2024-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(default='mthandazomoyo75@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
